# Generated by Django 2.2.2 on 2019-11-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('sub_title', models.CharField(max_length=225)),
                ('discription', models.TextField()),
                ('view_count', models.IntegerField()),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('file_copy', models.FileField(null=True, upload_to='')),
                ('cover_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
