# Generated by Django 2.2.2 on 2019-11-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectname',
            name='project_type',
            field=models.CharField(choices=[('hardware', 'hardware'), ('Django Webpage', 'Django Webpage'), ('logo', 'logo'), ('Diy', 'Diy'), ('Desktop', 'Desktop')], default=1, max_length=16),
            preserve_default=False,
        ),
    ]
