# Generated by Django 2.2.2 on 2019-11-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectname_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectname',
            name='discription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projectname',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
