# Generated by Django 2.2.2 on 2019-11-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20191106_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectname',
            name='project_type',
            field=models.CharField(choices=[('hardware', 'hardware'), ('DjangoWebpage', 'DjangoWebpage'), ('logo', 'logo'), ('Diy', 'Diy'), ('Desktop', 'Desktop')], max_length=16),
        ),
    ]
