# Generated by Django 2.2.2 on 2020-08-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
