# Generated by Django 2.2.2 on 2020-08-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0002_personaldata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='current_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
